name: Secure Deploy
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject Secrets
        env:
          MY_TOKEN: ${{ secrets.GH_PAT }}
          MY_USER: ${{ github.repository_owner }}
          MY_REPO: ${{ github.event.repository.name }}
        run: |
          # We use '|' as a delimiter to avoid issues with special characters in tokens
          sed -i "s|PLACEHOLDER_TOKEN|$MY_TOKEN|g" js/api.js
          sed -i "s|PLACEHOLDER_USER|$MY_USER|g" js/api.js
          sed -i "s|PLACEHOLDER_REPO|$MY_REPO|g" js/api.js

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
